project:
  type: website
  output-dir: docs

website:
  title: "GeoReDUS - Domic√≠lios"
  navbar:
    left:
      - href: index.qmd
        text: Sobre
      - href: 01-import-data.qmd
        text: "Dados"
      - href: 02-indicators.qmd
        text: "Indicators"  
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual